#  NumPy contains multidimensional array and matrix data structures, as well as functions to manipulate them. You'll learn more about these data structures and functions soon, but for now, let's just consider NumPy at a high level and learn more about it. NumPy's power comes from vectorization. Vectorization enables operations to be performed on multiple components of a data object at the same time

In [1]:
list1=[1,2,3]
list2=[4,5,6]
list3=[]
#list3=list1+list2#throws error
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])
print(list3)

[5, 7, 9]


In [2]:
#we can do the same thing easily using numpy
import numpy as np
array1=np.array(list1)
array2=np.array(list2)
array1+array2

array([5, 7, 9])

In [3]:
#let's create an array from a list
myarr=np.array([3,4,5])#here we can see there is only one square bracket so one dimensional array is formed
print(myarr)

[3 4 5]


In [4]:
myarr.shape

(3,)

In [5]:
myarr[0]

3

In [7]:
#lets make a two dimensional array
arr=np.array([[2,3,4]])
arr

array([[2, 3, 4]])

In [16]:
"""now it has bexome a two dimensional array and while accessing the value we should provide the two coordinates staring
with o i.e. the 0th row and 0th column, 0th row and 1st column etc"""
print(arr[0,0])
print("\n",arr[0,1])

2

 3


In [17]:
#we can change the values in the array with the help of their index
arr[0,1]=5
print(arr)

[[2 5 4]]


In [19]:
#we can also make arrays by converting from other python structures like lists and tuples

listarray=np.array([[1,2,3],[2,3,4],[4,5,6]])
tuplesarray=np.array([(44,55,66),(99,33,54)])
print(listarray,end="\n")
print(tuplesarray)

[[1 2 3]
 [2 3 4]
 [4 5 6]]
[[44 55 66]
 [99 33 54]]


In [23]:
listarray.shape



(3, 3)

In [24]:
zeros=np.zeros([3,3])

In [25]:
zeros#so the above code helps us creating the array of dimension 3x3 with elements all zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
#some other functions
sk=np.arange(10)
sk

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#linspace function helps us creating array from a certain number upto another number with same spacing inbetween 
lspace=np.linspace(0,5,11)
lspace

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [33]:
#np.empty()fills the empty array of certain dimension with random numbers
emp=np.empty((3,3))

In [34]:
emp


array([[0.55555556, 1.11111111, 1.66666667],
       [2.22222222, 2.77777778, 3.33333333],
       [3.88888889, 4.44444444, 5.        ]])

In [35]:
empL=np.empty_like(emp)

In [37]:
empL

array([[0.55555556, 1.11111111, 1.66666667],
       [2.22222222, 2.77777778, 3.33333333],
       [3.88888889, 4.44444444, 5.        ]])

In [40]:
l1=[3,4,5]
l2=[5,4,6]
l3=[6,7,8]
l4=[9,2,3]
jk=np.array((l1,l2))
sk=np.array([l3,l4])

In [43]:
jk+sk#you can add the 2d arrays like this


array([[ 9, 11, 13],
       [14,  6,  9]])

In [ ]:
# Creating a list of lists
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Accessing elements
print(list_of_lists[0])  # Output: [1, 2, 3]
print(list_of_lists[1][2])  # Output: 6

# Modifying elements
list_of_lists[2][1] = 10
print(list_of_lists)  # Output: [[1, 2, 3], [4, 5, 6], [7, 10, 9]]

# Iterating over elements
for sublist in list_of_lists:
    for element in sublist:
        print(element)


In [44]:
jk

array([[3, 4, 5],
       [5, 4, 6]])

In [46]:
jk.sum(axis=0)#adds vertically or along the rows 

array([ 8,  8, 11])

In [47]:
jk.sum(axis=1)#adds horizontally or along the columns


array([12, 15])

In [49]:
jk.T#transpose 

array([[3, 5],
       [4, 4],
       [5, 6]])

In [50]:
jk.flat#gives iterator means now our array can be iterated

In [51]:
for i in jk.flat:
    print(i)

3
4
5
5
4
6


In [52]:
jk.ndim #let us know which dimensional array it is

2

In [55]:
jk.argmax()#gives the indexx of the maximum value

array([1, 0, 1], dtype=int64)

In [58]:
jk.argmax(axis=1)#gives the index of each maximum value in rows

array([2, 2], dtype=int64)

In [59]:
jk.argmax(axis=0)#gives the index of each maximum value in columns

array([1, 0, 1], dtype=int64)

In [70]:
listt=[1,2,3]
hk=np.array(listt)

In [71]:
hk

array([1, 2, 3])

# accessing and changing specific elements ,rows and columns 

In [72]:
sijan=np.array([[1,2,3,4],[3,4,5,6],[9,8,7,6]])
print(sijan)

[[1 2 3 4]
 [3 4 5 6]
 [9 8 7 6]]


In [73]:
sijan.shape

(3, 4)

In [74]:
#get a specific element suppose we want to get 5 from second row
sijan[1,2]

5

In [78]:
#get a specific row suppose we want to get third row
sijan[2]

array([9, 8, 7, 6])

In [81]:
#get a specific column supose we want to get second column
sijan[:,1] #: specifies all the rows in the array and 1 indicates the second column

array([2, 4, 8])

In [83]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [84]:
np.full((3,3),88)

array([[88, 88, 88],
       [88, 88, 88],
       [88, 88, 88]])

In [85]:
np.full(sijan.shape,3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [86]:
np.full_like(sijan,5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [87]:
#random decimal number
np.random.rand(2,3)

array([[0.46635234, 0.66426024, 0.76457099],
       [0.35788602, 0.92313588, 0.21650639]])

In [88]:
np.random.sample(sijan.shape)

array([[0.94435693, 0.40084014, 0.48112691, 0.48172081],
       [0.45514795, 0.93179621, 0.75378463, 0.41751618],
       [0.49860832, 0.53437012, 0.10441117, 0.39729426]])

In [91]:
#random integer numbers (upto what no, size=(a,b))
np.random.randint(8,size=(3,3))

array([[4, 4, 6],
       [4, 4, 0],
       [7, 2, 5]])

In [93]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [101]:
je=[1,2,3]
k=np.array([[je]])
print(k)

[[[1 2 3]]]


In [102]:
k.ndim

3

In [103]:
#repeat an array

arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)

In [104]:
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [118]:
""" we want 1 1 1 1 
            1 0 9 1
            1 9 0 1
            1 1 1 1 
"""
a=np.ones((4,4))
print(a)
b=np.zeros((2,2))
b[0,1]=9
b[1,0]=9#it says zeroth row first column and first column zeroth row
print(b)
a[1:3,1:3]=b
print(a)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 9.]
 [9. 0.]]
[[1. 1. 1. 1.]
 [1. 0. 9. 1.]
 [1. 9. 0. 1.]
 [1. 1. 1. 1.]]


# mathematics


In [119]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [120]:
a+2#adds every element with two

array([3, 4, 5, 6, 7, 8])

# linear algebra

In [124]:
a=np.ones((2,3))

print(a)
b=np.full((3,2),2)
print(b)


np.matmul(a,b)#matrix multiplication but note we cannot just multiply a*b with different dimensions

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [125]:
c=np.ones((3,3))
d=np.full((3,3),2)
c*d

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [129]:
i=np.identity(3)
i
print(np.linalg.det(i))# linalg= linear algebra and det=determinant

1.0


# statistics

In [130]:
simple=np.array([[1,2,3],[3,4,5]])
simple

array([[1, 2, 3],
       [3, 4, 5]])

In [132]:
np.min(simple)

1

In [133]:
np.max(simple)

5

In [134]:
np.max(simple,axis=1)

array([3, 5])

In [140]:
np.max(simple,axis=0)

array([3, 4, 5])

In [141]:
np.sum(simple)

18

# reorganizing arrays

In [152]:
before=np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6]])
print(before)
after=before.reshape((2,3,2))# three dim
print(after)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]]
[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 8]
  [7 6]]]


In [153]:
#vertically stacking vectors 
v1=np.array([22,23,24])
v2=np.array([34,345,67])

np.vstack([v1,v2,v1,v2])# vstack=vertically stack

array([[ 22,  23,  24],
       [ 34, 345,  67],
       [ 22,  23,  24],
       [ 34, 345,  67]])

In [157]:
#horizontal stack
h1=np.array([[44,33]])
h2=np.ones((1,2))
np.hstack([h1,h2])

array([[44., 33.,  1.,  1.]])

# load data from file 

In [169]:
filedata=np.genfromtxt('sijan.txt',delimiter=',')
filedata.astype('int32')#originally they come as float but we can change them into desired datatype by using astype function


array([  1,   2,   3,   4,   5,   6,   7,   5, 544,  33,  22,  44,  55,
        66,  77,  55,  44, 333, 223, 445, 343, 222])

In [171]:
#boolean masking and advanced indexing
filedata<50

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False, False, False, False,  True, False,
       False, False, False, False])

In [172]:
filedata[filedata<50]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  5., 33., 22., 44., 44.])

In [174]:
np.all(filedata<50,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1